service: anibot
 
provider: # Required to tell serverless this is an aws project, modify as needed
  name: aws
  runtime: python3.8
  # Modify the following with real aws profile to deploy to aws
  # Add more attributes as needed to suit your aws environment, eg. region
  stage: prod
  profile: botprofile
  logRetentionInDays: 14
  environment:
    ANIBOT_TOKEN: ${env:ANIBOT_TOKEN}

# Configure your lambda function(s) here
functions:
  trigger:
    maximumRetryAttempts: 0
    handler: handler.trigger
    events:
      - http:
          path: /trigger
          method: post
          async: true

package:
  exclude:
    - ./node_modules
    - ./local.py
    - setWebhook

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    slim: true
    pythonBin: python3
